### ISSUE TITLE
On play/pause, time into current song incorrect. 

### ISSUE THREAD

**Issue by jakes44** [jcm93/jmc#31] opened 2017-11-14 20:55 UTC
<img width="1440" alt="screen shot 2017-11-14 at 3 52 01 pm" src="https://user-images.githubusercontent.com/15040414/32804121-e845f6de-c953-11e7-9f75-606d13c19084.png">

Still looking to replicate consistently, but have noticed when I play and pause a song several times that jmc often has the time into the current playing song incorrect. It seems to be the total time I have been listening, rather than the just the portion of the song that has been played. In the image above it says I am 22 minutes into a 6 and half minute song. 

<img width="654" alt="screen shot 2017-11-14 at 4 02 05 pm" src="https://user-images.githubusercontent.com/15040414/32804500-3d746ed2-c955-11e7-80e2-bfe6e0301e2c.png">

**Comment by jakes44** [comment] 2017-11-14 20:56
Will look into this a little later

**Comment by jcm93** [comment] 2017-11-29 00:43
Looks like an issue with gapless FLAC playback. Looking into it.

**Comment by jcm93** [comment] 2017-11-29 00:50
I can't reproduce it on my machine. Can you confirm this is happening with the latest release?

**Comment by jakes44** [comment] 2017-11-29 00:53
Happening on v0.2 beta 5

**Comment by jcm93** [comment] 2017-12-07 06:44
Should be fixed with the release of the latest beta 6. Please reopen if the issue persists.

**Closed by jcm93** 2017-12-07 06:44 UTC
